"""
teams.py — Central team configuration for all 30 MLB teams.

Import this module everywhere instead of scattered constants.

Usage:
    from teams import TEAMS, SEASON, get_team
    cfg = get_team('ARI')   # returns dict with team metadata
"""

SEASON = 2025

# ---------------------------------------------------------------------------
# All 30 MLB teams
# Keys:
#   mlb_team_id   - MLB Stats API teamId
#   statcast_code - home_team column value in Statcast / pitches table
#   fg_code       - FanGraphs / pybaseball team code
#   spotrac_slug  - Spotrac URL slug for payroll scraping
#   full_name     - Full official team name
#   short_name    - Short nickname for UI labels
#   season_start  - Statcast pull start date (regular season)
#   season_end    - Statcast pull end date
# ---------------------------------------------------------------------------

TEAMS: dict[str, dict] = {
    'ARI': {
        'mlb_team_id':   109,
        'statcast_code': 'AZ',
        'fg_code':       'ARI',
        'spotrac_slug':  'arizona-diamondbacks',
        'full_name':     'Arizona Diamondbacks',
        'short_name':    'D-backs',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'ATL': {
        'mlb_team_id':   144,
        'statcast_code': 'ATL',
        'fg_code':       'ATL',
        'spotrac_slug':  'atlanta-braves',
        'full_name':     'Atlanta Braves',
        'short_name':    'Braves',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'BAL': {
        'mlb_team_id':   110,
        'statcast_code': 'BAL',
        'fg_code':       'BAL',
        'spotrac_slug':  'baltimore-orioles',
        'full_name':     'Baltimore Orioles',
        'short_name':    'Orioles',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'BOS': {
        'mlb_team_id':   111,
        'statcast_code': 'BOS',
        'fg_code':       'BOS',
        'spotrac_slug':  'boston-red-sox',
        'full_name':     'Boston Red Sox',
        'short_name':    'Red Sox',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'CHC': {
        'mlb_team_id':   112,
        'statcast_code': 'CHC',
        'fg_code':       'CHC',
        'spotrac_slug':  'chicago-cubs',
        'full_name':     'Chicago Cubs',
        'short_name':    'Cubs',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'CWS': {
        'mlb_team_id':   145,
        'statcast_code': 'CWS',
        'fg_code':       'CWS',
        'spotrac_slug':  'chicago-white-sox',
        'full_name':     'Chicago White Sox',
        'short_name':    'White Sox',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'CIN': {
        'mlb_team_id':   113,
        'statcast_code': 'CIN',
        'fg_code':       'CIN',
        'spotrac_slug':  'cincinnati-reds',
        'full_name':     'Cincinnati Reds',
        'short_name':    'Reds',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'CLE': {
        'mlb_team_id':   114,
        'statcast_code': 'CLE',
        'fg_code':       'CLE',
        'spotrac_slug':  'cleveland-guardians',
        'full_name':     'Cleveland Guardians',
        'short_name':    'Guardians',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'COL': {
        'mlb_team_id':   115,
        'statcast_code': 'COL',
        'fg_code':       'COL',
        'spotrac_slug':  'colorado-rockies',
        'full_name':     'Colorado Rockies',
        'short_name':    'Rockies',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'DET': {
        'mlb_team_id':   116,
        'statcast_code': 'DET',
        'fg_code':       'DET',
        'spotrac_slug':  'detroit-tigers',
        'full_name':     'Detroit Tigers',
        'short_name':    'Tigers',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'HOU': {
        'mlb_team_id':   117,
        'statcast_code': 'HOU',
        'fg_code':       'HOU',
        'spotrac_slug':  'houston-astros',
        'full_name':     'Houston Astros',
        'short_name':    'Astros',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'KC': {
        'mlb_team_id':   118,
        'statcast_code': 'KC',
        'fg_code':       'KC',
        'spotrac_slug':  'kansas-city-royals',
        'full_name':     'Kansas City Royals',
        'short_name':    'Royals',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'LAA': {
        'mlb_team_id':   108,
        'statcast_code': 'LAA',
        'fg_code':       'LAA',
        'spotrac_slug':  'los-angeles-angels',
        'full_name':     'Los Angeles Angels',
        'short_name':    'Angels',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'LAD': {
        'mlb_team_id':   119,
        'statcast_code': 'LAD',
        'fg_code':       'LAD',
        'spotrac_slug':  'los-angeles-dodgers',
        'full_name':     'Los Angeles Dodgers',
        'short_name':    'Dodgers',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'MIA': {
        'mlb_team_id':   146,
        'statcast_code': 'MIA',
        'fg_code':       'MIA',
        'spotrac_slug':  'miami-marlins',
        'full_name':     'Miami Marlins',
        'short_name':    'Marlins',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'MIL': {
        'mlb_team_id':   158,
        'statcast_code': 'MIL',
        'fg_code':       'MIL',
        'spotrac_slug':  'milwaukee-brewers',
        'full_name':     'Milwaukee Brewers',
        'short_name':    'Brewers',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'MIN': {
        'mlb_team_id':   142,
        'statcast_code': 'MIN',
        'fg_code':       'MIN',
        'spotrac_slug':  'minnesota-twins',
        'full_name':     'Minnesota Twins',
        'short_name':    'Twins',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'NYM': {
        'mlb_team_id':   121,
        'statcast_code': 'NYM',
        'fg_code':       'NYM',
        'spotrac_slug':  'new-york-mets',
        'full_name':     'New York Mets',
        'short_name':    'Mets',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'NYY': {
        'mlb_team_id':   147,
        'statcast_code': 'NYY',
        'fg_code':       'NYY',
        'spotrac_slug':  'new-york-yankees',
        'full_name':     'New York Yankees',
        'short_name':    'Yankees',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'ATH': {
        'mlb_team_id':   133,
        'statcast_code': 'ATH',
        'fg_code':       'ATH',
        'spotrac_slug':  'oakland-athletics',
        'full_name':     'Athletics',
        'short_name':    'Athletics',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'PHI': {
        'mlb_team_id':   143,
        'statcast_code': 'PHI',
        'fg_code':       'PHI',
        'spotrac_slug':  'philadelphia-phillies',
        'full_name':     'Philadelphia Phillies',
        'short_name':    'Phillies',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'PIT': {
        'mlb_team_id':   134,
        'statcast_code': 'PIT',
        'fg_code':       'PIT',
        'spotrac_slug':  'pittsburgh-pirates',
        'full_name':     'Pittsburgh Pirates',
        'short_name':    'Pirates',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'SD': {
        'mlb_team_id':   135,
        'statcast_code': 'SD',
        'fg_code':       'SD',
        'spotrac_slug':  'san-diego-padres',
        'full_name':     'San Diego Padres',
        'short_name':    'Padres',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'SF': {
        'mlb_team_id':   137,
        'statcast_code': 'SF',
        'fg_code':       'SF',
        'spotrac_slug':  'san-francisco-giants',
        'full_name':     'San Francisco Giants',
        'short_name':    'Giants',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'SEA': {
        'mlb_team_id':   136,
        'statcast_code': 'SEA',
        'fg_code':       'SEA',
        'spotrac_slug':  'seattle-mariners',
        'full_name':     'Seattle Mariners',
        'short_name':    'Mariners',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'STL': {
        'mlb_team_id':   138,
        'statcast_code': 'STL',
        'fg_code':       'STL',
        'spotrac_slug':  'st-louis-cardinals',
        'full_name':     'St. Louis Cardinals',
        'short_name':    'Cardinals',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'TB': {
        'mlb_team_id':   139,
        'statcast_code': 'TB',
        'fg_code':       'TB',
        'spotrac_slug':  'tampa-bay-rays',
        'full_name':     'Tampa Bay Rays',
        'short_name':    'Rays',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'TEX': {
        'mlb_team_id':   140,
        'statcast_code': 'TEX',
        'fg_code':       'TEX',
        'spotrac_slug':  'texas-rangers',
        'full_name':     'Texas Rangers',
        'short_name':    'Rangers',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'TOR': {
        'mlb_team_id':   141,
        'statcast_code': 'TOR',
        'fg_code':       'TOR',
        'spotrac_slug':  'toronto-blue-jays',
        'full_name':     'Toronto Blue Jays',
        'short_name':    'Blue Jays',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
    'WSH': {
        'mlb_team_id':   120,
        'statcast_code': 'WSH',
        'fg_code':       'WSH',
        'spotrac_slug':  'washington-nationals',
        'full_name':     'Washington Nationals',
        'short_name':    'Nationals',
        'season_start':  '2025-03-27',
        'season_end':    '2025-10-01',
    },
}


def get_team(code: str) -> dict:
    """Return team config dict for the given code, or raise KeyError."""
    return TEAMS[code.upper()]
